<?php

namespace Sts\Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerMatchRepository extends EntityRepository
{
}
